#index:
#    path: /
#    controller: App\Controller\DefaultController::index

auth_url:
    path: /api/v1/auth/link
    controller: App\Controller\AuthController::getAuthLink
    methods: GET
auth_user:
    path: /api/v1/auth
    controller: App\Controller\AuthController::authUser
    methods: GET
current_playing:
    path: /api/v1/user/playing
    controller: App\Controller\UserController::currentPlaying
    methods: GET 
song_facts:
    path: /api/v1/song/stats
    controller: App\Controller\SongsStatsController::getStats
    methods: GET 